# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

env:
  - R_MY_PKG="$(basename $TRAVIS_REPO_SLUG)"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package jimhester/covr
script: 
  - ./travis-tool.sh run_tests

after_success:
  - ls
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change